### ISSUE TITLE
Question about the paper usad

### ISSUE THREAD

**Issue by KcAcoZhang** [JulienAu/Anomaly_Detection_Tuto#1]
Dear Author,
I tried to contact you by email address @orange, but the address was "Cette boîte mail est désactivée. Elle ne peut plus recevoir de message."  I can see that you calculate the anomaly score with parameters alpha and beta. May I ask how you calculate the threshold lamda in your method USAD.

**Comment by JulienAu** [comment]
Replied by mail. The issue does not correspond to this repo.
